from . import (
    test_controller,
    test_utils,
    test_base,
    test_example,
    test_routing_manager,
    test_base_extra,
    test_evolution,
    test_code_hooks,
    test_models,
    test_bot_manager,
    test_res_partner,
    test_create_user_for_visitor,
    test_guest_channel_creation,
    test_webhook_user_creation,
    test_simple,
)
